import { createApp } from 'vue';
import App from './App.vue';
import NewsGearsWebPlugin from '@/newsgears-web/newsgears-web-plugin';
import NewsGearsThemePlugin from '@/newsgears-theme/newsgears-theme-plugin';
import router from './router';
import { autoAnimatePlugin } from '@formkit/auto-animate/vue';
import VuePlyr from 'vue-plyr';
import VueAnnouncer from '@vue-a11y/announcer';
import { createI18n } from 'vue-i18n';
import Vue3NativeNotification from 'vue3-native-notification'

import '@vue-a11y/announcer/dist/style.css';
import 'vue-plyr/dist/vue-plyr.css';
import 'font-awesome/scss/font-awesome.scss';
import 'flag-icons/css/flag-icons.min.css';
import './registerServiceWorker';

let lang = window.navigator.languages ? window.navigator.languages[0] : null;
    lang = lang || window.navigator.language || window.navigator.browserLanguage || window.navigator.userLanguage;

let shortLang = lang;
if (shortLang.indexOf('-') !== -1)
    shortLang = shortLang.split('-')[0];

if (shortLang.indexOf('_') !== -1)
    shortLang = shortLang.split('_')[0];

const i18n = createI18n({
  locale: shortLang,
  fallbackLocale: 'en',
  allowComposition: true, 
  messages: {
    es: {
      // generic 
      somethingHorribleHappened: 'Algo horrible sucedió. Vuelva a intentarlo en unos momentos.',
      privacyPolicy: 'Política de Privacidad',
      cancel: 'Cancelar',
      filter: 'Filtrar',
      first: 'Primer artículo',
      previous: 'Artículo anterior',
      next: 'Artículo siguiente',
      last: 'último artículo',
      username: 'Nombre de usuario',
      password: 'Contraseña',
      submit: 'Entregar',
      subscribe: 'Suscribe',
      subscribed: '¡Suscrito!',
      emailAddress: 'Dirección de correo electrónico',
      inDevelopment: 'Lo sentimos, esta sección de FeedGears aún no está lista. ¡Vuelve a consultar en unos días!',
      // auth 
      accountRecovery: 'Recuperación de Cuenta',
      registerHere: 'FeedGears es gratis. Crea una cuenta aquí.',
      unableToCompleteYourRequest: 'No pudimos completar su solicitud. Intente iniciar sesión con otro método.',
      usernameAndPasswordAreRequired: 'Se requiere nombre de usuario y contraseña.',
      passwordIsRequired: 'Se requiere contraseña.',
      usernameIsRequired: 'Se requiere nombre de usuario.',
      signinWithGoogle: 'Inicia sesión con Google',
      pwResetRequestMessage: 'Ingresa tu nombre de usuario y tu dirección de correo electrónico. Le enviaremos un enlace de restablecimiento de contraseña a su dirección de correo electrónico verificada.',
      checkEmailForFurther: 'Revise su correo electrónico para obtener más instrucciones.',
      newPassword: 'Nueva contraseña',
      confirmNewPassword: 'Confirmar nueva contraseña',
      enterAndConfirmNewPw: 'Ingresa y confirma tu nueva contraseña.',
      pwUpdated: 'Contraseña actualiza.',
      registrationRequirements: 'Se requiere nombre de usuario, dirección de correo electrónico y contraseña para registrarse.',
      youHaveBeenLoggedOut: 'Has sido desconectado.',
      clickHereToStartOver: 'Haga clic aquí para empezar de nuevo.',
      // landing
      createAnAccount: 'Crear una cuenta',
      whatIsFeedGears: 'Un lector de feeds seguro, privado y accesible.',
      whyIsFeedGearsFree: 'FeedGears es gratis porque creemos en RSS',
      devBlog: 'Blog de desarrollo',
      docs: 'Documentos',
      api: 'API',
      email: 'Correo electrónico',
      twitter: 'Twitter',
      github: 'Github',
      twitch: 'Contracción',
      discord: 'Discordia',
      copyright: 'DERECHOS DE AUTOR',
      contactUsWithQuestionsViaEmail: 'Comuníquese con Lost Sidewalk Software si tiene preguntas por correo electrónico',
      // confirmation dialog 
      confirm: 'Confirmar',
      // go back
      goBack: 'Regresa.',
      // min-max
      collapseThisPanel: 'Contraer este panel',
      restoreThisPanel: 'Restaurar este panel',
      // navbar button components 
      login: 'Acceso', 
      logout: 'Cerrar sesión',
      settings: 'Ajustes',
      help: 'Ayuda', 
      switchMode: 'Cambiar el modo de visualización',
      cycleGridLayout: 'Cambiar al diseño de cuadrícula',
      cycleTableLayout: 'Cambiar a diseño tabular',
      // queue dashboard buttons 
      createNewQueue: 'Crear una nueva cola',
      uploadOPML: 'Subir OPML',
      weWillNotSellOrDiscloseYourInformation: 'Tenga en cuenta que nunca venderemos ni divulgaremos su información personal a nadie.',
      // queue select button 
      showMoreInfo: 'Mostrar suscripciones',
      hideMoreInfo: 'Ocultar suscripciones',
      addSubscriptions: 'Agregar suscripciones',
      manageSubscriptions: 'Administrar suscripciones',
      deleteThisQueue: 'Eliminar esta cola',
      subscriptions: 'SUSCRIPCIONES',
      publications: 'PUBLICACIONES',
      zeroSubscriptions: '0 suscripciones',
      starredArticlesAvailableHere: 'Los artículos destacados en esta cola están disponibles en las siguientes fuentes RSS.',
      metricsNotYetAvailable: 'Las métricas aún no están disponibles para esta fuente RSS.',
      // queue config image field 
      clickToChangeQueueImage: 'Haga clic aquí para cambiar la imagen de la cola.',
      clickToAddQueueImage: 'Haga clic aquí para agregar una imagen de cola.', 
      unableToFetchAnImage: 'No pudimos obtener una imagen. Por favor, inténtelo de nuevo más tarde.',
      unableToUseThisImage: 'No pudimos usar esta imagen. Pruebe con otro y tenga en cuenta que el tamaño máximo para los archivos de imagen es de 1M.',
      // queue config panel 
      queueIdentifier: 'Identificador de cola', 
      queueIdentifierHelpText: 'El identificador de cola es una breve descripción textual de esta cola. No distingue entre mayúsculas y minúsculas y debe contener solo números, letras, guiones o guiones bajos. Este identificador se puede usar para ubicar el feed destacado para esta cola. Haga clic para obtener más información.',
      queueTitle: 'título de la cola', 
      queueTitleHelpText: 'El título de la cola es una descripción textual de esta cola que aparece en el panel de la cola.',
      queueImage: 'imagen de la cola', 
      queueDescription: 'Descripción de la cola', 
      queueDescriptionHelpText: 'Este valor es una descripción textual más detallada de esta cola. Aparece en el feed RSS/ATOM publicado para esta cola.',
      queueFeedGenerator: 'Generador', 
      queueFeedGeneratorHelpText: 'Este valor aparece como \'generator\' en la fuente RSS/ATOM publicada para esta cola.',
      queueFeedCopyright: 'Derechos de autor', 
      queueFeedCopyrightHelpText: 'Este valor aparece como \'copyright\' en la fuente RSS/ATOM publicada para esta cola.',
      queueFeedLanguage: 'Idioma', 
      queueFeedLanguageHelpText: 'Este valor aparece como el valor del campo \'idioma\' en la fuente RSS/ATOM publicada para esta cola.',
      fillOutAllRequiredFields: 'Rellene todos los campos obligatorios',
      // tooltips 
      updateThisQueue: 'Actualizar esta cola',
      updateThisQueueAndClose: 'Actualizar esta cola y cerrar',
      // buttons 
      update: 'Actualizar',
      updateAndClose: 'Actualizar y cerrar',
      // tooltips 
      saveThisQueue: 'Guardar esta cola',
      saveThisQueueAndClose: 'Guardar esta cola y cerrar',
      // buttons 
      save: 'Guardar',
      saveAndClose: 'Guardar y cerrar',
      // 
      queueProperties: 'Propiedades de la cola',
      rssFeedDiscovery: 'Descubrimiento de fuentes RSS',
      // rss feed info 
      toggleAuthorFilter: 'Alternar el filtrado en este autor',
      authorColon: 'Autor:',
      lastPublishedColon: 'Última publicación:',
      toggleCategoryFilter: 'Alternar filtrado en esta categoría', 
      toggleLanguageFilter: 'Alternar filtrado en este idioma',
      toggleDocStringFilter: 'Alternar filtrado en esta cadena de documentación',
      toggleEncodingFilter: 'Alternar filtrado en esta codificación',
      toggleManagingEditorFilter: 'Alternar filtro por este editor gerente',
      managingEditorColon: 'Editor gerente:', 
      toggleWebmasterFilter: 'Alternar el filtrado en este webmaster', 
      webmasterColon: 'Administrador de página web:', 
      httpStatusCode: 'Código de estado HTTP',
      redirectHttpStatusCode: 'Redirigir el código de estado HTTP', 
      feedAlsoAvailableInHttps: 'Este feed también está disponible en HTTPS.', 
      sampleEntries: 'Artículos recientes',
      recommendedFeeds: 'Fuentes RSS similares',
      // feed collections browser 
      loadingCollections: 'CARGANDO COLECCIONES...',
      browseCollectionsByCategory: 'EXPLORAR COLECCIONES POR CATEGORÍA',
      topNews: 'Noticias',
      investing: 'Invertir',
      technology: 'Tecnología',
      business: 'Negocio',
      science: 'Ciencia',
      creative: 'Creativo',
      lifestyle: 'Estilo de vida',
      // feed catalog 
      feedCatalog: 'CATÁLOGO DE FUENTES RSS',
      nFeedsMatchOnPageM: 'COINCIDENCIA DE FEEDS RSS, MOSTRANDO LA PÁGINA',
      categoryColon: 'Categoría:',
      languageColon: 'Idioma:',
      docsColon: 'Documentos:',
      encodingColon: 'Codificación:',
      feedTypeColon: 'Tipo de fuente RSS:',
      generatorColon: 'Generador:',
      removeThisFilter: 'Eliminar este filtro',
      subscribeToThisFeed: 'Suscríbete a esta fuente RSS',
      youAreSubscribed: '¡Suscrito!',
      // subscription config 
      yourSubscriptions: 'SUS SUSCRIPCIONES',
      showingPageN: 'Mostrando la página',
      addFeedFromURL: 'Agregar fuente RSS desde una URL',
      searchFeedCatalog: 'Buscar en el catálogo de fuentes RSS',
      browseFeedCollections: 'Explorar colecciones de fuentes RSS',
      subscriptionNofM: 'SUSCRIPCIÓN',
      addANewSubscription: 'AGREGAR UNA NEUVA SUSCRIPCIÓN',
      feedUrl: 'URL de fuente RSS',
      credentialsUseMessage: '* Se proporcionarán las siguientes credenciales si esta fuente RSS solicita autenticación.',
      unableToFetchCatalog: 'No pudimos obtener su catálogo de fuentes RSS. Por favor, inténtelo de nuevo más tarde.',
      discovery: 'Descubrimiento', 
      auth: 'Autorización',
      unsubscribe: 'Darse de baja',
      subscriptionAdded: 'Suscripción añadida',
      subscriptionUpdated: 'Suscripción actualizada',
      subscriptionDeleted: 'Suscripción eliminada',
      // post feed filter 
      articleQueue: 'COLA DE ARTÍCULOS',
      refreshQueues: 'Actualizar colas', 
      markQueueAsRead: 'Marcar esta cola como leída',
      toggleSortOrder: 'Alternar dirección de clasificación',
      showFilterOptions: 'Mostrar opciones de filtro', 
      // post feed filter pills 
      allSubscriptions: 'todas las suscripciones',
      viewingColon: 'Visita:',
      resetToDefault: 'Restablecen a los predeterminados',
      unread: 'NO LEÍDO', 
      readLater: 'LEER MÁS TARDE',
      read: 'LEÍDO',
      starred: 'SEMBRADO DE ESTRELLAS',
      // help panel 
      dismiss: 'Despedir',
      configureSelectedQueue: 'Administrar suscripciones en la cola seleccionada',
      markSelectedQueueAsRead: 'Marcar la cola seleccionada como leída',
      addSubscriptionToSelectedQueue: 'Agregar una suscripción a la cola seleccionada',
      starSelectedPost: 'Destacar la publicación seleccionada',
      toggleReadStatusSelectedPost: 'Alternar la publicación seleccionada leída/no leída',
      openOriginalArticleSelectedPost: 'Abrir la URL de la publicación seleccionada en una nueva pestaña',
      showUnread: 'Mostrar no leídos', 
      showStarred: 'Mostrar destacado',
      showReadLater: 'Mostrar leer más tarde',
      showRead: 'Mostrar leído',
      search: 'Buscar',
      // iTunes
      explicit: 'EXPLÍCITO',
      closedCaptioned: 'Subtitulado',
      // post media 
      media: 'MEDIOS DE COMUNICACIÓN', 
      // community 
      nViews: 'PUNTOS DE VISTA',
      tags: 'ETIQUETAS', 
      // post media content 
      audioChannelsColon: 'CANALES DE AUDIO:',
      bitRateColon: 'TASA DE BITS:',
      durationColon: 'DURACIÓN:',
      expressionColon: 'EXPRESIÓN:',
      fileSizeColon: 'TAMAÑO DEL ARCHIVO:',
      frameRateColon: 'CUADROS POR SEGUNDO:',
      heightColon: 'ALTURA:',
      widthColon: 'ANCHO:',
      samplingRateColon: 'TASA DE MUESTREO:',
      // opml 
      opmlFilesColon: 'ARCHIVOS OPML:',
      previewThisFile: 'Obtenga una vista previa de este archivo en una nueva ventana.', 
      opmlFilesContainErrors: 'Sus archivos contienen los siguientes problemas. Resuelva estos problemas y vuelva a intentar la carga.',
      weWillCreateTheFollowingSubscriptions: 'Crearemos las siguientes colas a partir de su(s) archivo(s) OPML:',
      selectAnOpmlFile: 'Seleccione un archivo OPML',
      addAnOpmlFile: 'Agregar un archivo OPML', 
      finalizeUpload: 'Finalizar carga',
      continue: 'Continuar',
      addAtLeastOneFile: 'Agregue al menos un archivo OPML para continuar.',
      continueToStep2: 'Continúe con el paso 2', 
      // post feed 
      confirmDeleteQueue: 'Confirme que desea eliminar esta cola. Esta acción es irreversible.', 
      confirmMarkQueueAsRead: 'Confirme que desea marcar todos los elementos de esta cola como leídos.', 
      queueDashboard: 'PANEL DE RSS', 
      noArticlesInQueue: 'No hay artículos en esta cola. Agregue suscripciones adicionales o espere a que se importen más artículos.', 
      endOfQueueReached: 'Has llegado al final de esta cola. Agregue suscripciones adicionales o espere a que se importen más artículos.', 
      queueSettings: 'AJUSTES DE COLA', 
      opmlUpload: 'CARGA OPML', 
      refreshFailedDueToColon: 'Actualizar falló debido a:',
      noMessage: 'sin mensaje',
      queueUpdated: 'Cola actualizada',
      queueCreated: 'Cola creada',
      nQueuesCreated: ' colas creadas',
      clickToLoadMore: 'Haga clic aquí para cargar más', 
      // post item 
      showPostDetails: 'Mostrar detalles de la publicación', 
      showPostCategories: 'Mostrar categorías de publicaciones',
      showPostSharing: 'Mostrar publicación compartida',
      shareWith_twitter: 'Compartir con Twitter',
      shareWith_facebook: 'Compartir con Facebook',
      shareWith_telegram: 'Compartir con Telegram',
      shareWith_linkedIn: 'Compartir con LinkedIn',
      shareWith_blogger: 'Compartir con Blogger',
      shareWith_buffer: 'Compartir con Buffer',
      shareWith_hootsuite: 'Compartir con Hootsuite',
      goToNextPost: 'Ir a la siguiente publicación',
      goToPreviousPost: 'Ir a la publicación anterior',
      goToFirstPost: 'Ir a la primera publicación',
      goToLastPost: 'Ir a la última publicación',
      markPostAsUnread: 'Marcar como no leído',
      markPostAsRead: 'Marcar como leído',
      markPostAsReadLater: 'Marcar como leído más tarde',
      unmarkPostAsReadLater: 'Desmarcar como leído más tarde', 
      starThisPost: 'Destacar esta publicación',
      unstarThisPost: 'Un-star this post',
      openOriginalArticle: 'Abrir artículo original',
      description: 'DESCRIPCIÓN',
      links: 'ENLACES', 
      postComments: 'COMENTARIOS', 
      author: 'AUTOR',
      authors: 'AUTORES', 
      updated: 'ACTUALIZADO',
      published: 'PUBLICADO',
      contributors: 'CONTRIBUYENTES', 
      // settings 
      accountSettings: 'CONFIGURACIONES DE LA CUENTA', 
      usernameColon: 'NOMBRE DE USUARIO:', 
      emailAddressColon: 'DIRECCIÓN DE CORREO ELECTRÓNICO:', 
      applyChanges: 'Aplicar cambios',
      deactivateYourAccount: 'Desactiva tu cuenta',
      downloadYourData: 'Descarga tus datos', 
      permanentlyDeleteYourAccount: 'Eliminar permanentemente su cuenta',
      sendPasswordResetEmail: 'Enviar correo electrónico de restablecimiento de contraseña', 
      resetPassword: 'Restablecer la contraseña',
      updateNotificationPreferences: 'Actualizar preferencias de notificación', 
      emailNotificationsAreDisabled: 'Las notificaciones por correo electrónico están actualmente deshabilitadas.',
      emailNotificationsAreEnabled: 'Las notificaciones por correo electrónico están habilitadas actualmente.',
      enableAccountAlertsNotifications: 'Habilite esta opción para recibir alertas de cuenta y notificaciones de mantenimiento.',
      enableProductNotifications: 'Habilite esta opción para recibir correos electrónicos ocasionales sobre notificaciones de producción y nuevas funciones.',
      enableSelectedNotifications: 'Habilitar notificaciones seleccionadas',
      disableSelectedNotifications: 'Deshabilitar todas las notificaciones', 
      yourSubscriptionWasCanceled: 'Su suscripción fue cancelada y no se renovará.',
      currentPeriod: 'PERÍODO ACTUAL',
      endedAt: 'TERMINÓ EN',
      willEndAt: 'TERMINARÁ EN',
      statusColon: 'ESTADO:',
      amountDueColon: 'IMPORTE DEBIDO:',
      amountPaidColon: 'CANTIDAD PAGADA:',
      amountRemainingColon: 'CANTIDAD RESTANTE:',
      customerEmailAddressColon: 'DIRECCIÓN DE CORREO ELECTRÓNICO DEL CLIENTE:',
      customerNameColon: 'NOMBRE DEL CLIENTE:',
      invoiceUrlColon: 'URL DE LA FACTURA:',
      productColon: 'PRODUCTO:',
      mostRecentInvoice: 'FACTURA MAS RECIENTE',
      clickHere: 'haga clic aquí', 
      cancelSubscription: 'Cancelar suscripción',
      resumeSubscription: 'Reanudar suscripción',
      pleaseConsiderSubscribing: 'Considere suscribirse a FeedGears. Estamos respaldados al 100% por la comunidad de usuarios.',
      checkout: 'Verificar',
      settingsUpdated: 'Ajustes actualizan', 
      updateLightTheme: 'Haga clic aquí para guardar sus cambios en el tema de la luz',
      updateDarkTheme: 'Haga clic aquí para guardar sus cambios en el tema oscuro',
      themeSettingsUpdated: 'Configuración del tema actualizada', 
      opmlExportDownloaded: 'Exportación OPML descargada',
      yourSubscriptionWasCanceledClickToResume: 'Su suscripción fue cancelada. Para reanudar, haga clic en \'Reanudar suscripción\' en esta página.', 
      yourSubscriptionWasResumed: 'Tu suscripción fue reanudada',
      // docs 
      feedGearsDocumentation: 'DOCUMENTACIÓN DE ENGRANAJES', 
      // api 
      feedGearsApi: 'FEEDGEARS API',
      // order confirmation
      thankYouForYourOrder: 'GRACIAS POR SU ORDEN',
      yourOrderIsConfirmed: 'Su pedido está confirmado.',
      clickHereToReturnToTheApp: 'Haga clic aquí para volver a la aplicación.', 
      // verification callback 
      thanksForVerifying: '¡Gracias por verificar! El estado de su cuenta ha sido actualizado.',
      // privacy policy 
      feedGearsPrivacyPolicy: 'POLÍTICA DE PRIVACIDAD DE ALIMENTADORES', 
      whatInformationDoWeCollect: '¿Qué información recopilamos?',
      whatWeCollectSummary: 'Recopilamos información personal que usted nos proporciona.',
      whatWeCollectDetails: 'Recopilamos información personal que usted proporciona voluntariamente para usar cuando se registra en FeedGears, expresa interés en obtener información sobre nosotros o FeedGears, cuando participa en actividades en FeedGears o cuando se comunica con nosotros.',
      whatWeCollectImportantDetails: 'No procesamos información sensible.', 
      whatWeCollectFurtherDetails: 'Toda la información personal que nos proporcione debe ser verdadera, completa y precisa, y debe notificarnos cualquier cambio en dicha información personal.', 
      someCollectionIsAutomatic: 'Parte de la información se recopila automáticamente',
      automaticCollectionDetails: 'Parte de la información, como su dirección de Protocolo de Internet (IP) y/o las características del navegador y del dispositivo, se recopila automáticamente cuando visita FeedGears. Esta información (sistema operativo, preferencias de idioma, URL de referencia, nombre del dispositivo, país, ubicación, información sobre cómo y cuándo usa FeedGears y otra información técnica) no revela su identidad específica (como su nombre o información de contacto), pero puede incluir Información del dispositivo y uso. Esta información se necesita principalmente para mantener la seguridad y el funcionamiento de FeedGears, y para nuestros fines de informes y análisis internos.', 
      howDoWeProcess: '¿Cómo procesamos su información?',
      howDoWeProcessSummary: 'Procesamos su información para proporcionar, mejorar y administrar FeedGears, comunicarnos con usted, para seguridad y prevención de fraude, y para cumplir con la ley. También podemos procesar su información para otros fines con su consentimiento.',
      socialLogins: 'Inicios de sesión sociales',
      socialLoginsSummary: 'FeedGears le ofrece la posibilidad de registrarse e iniciar sesión utilizando los detalles de su cuenta de redes sociales de terceros (como los inicios de sesión de Google o Github). Cuando elija hacer esto, recibiremos cierta información de su perfil de su proveedor de redes sociales. La información de perfil que recibimos puede variar según el proveedor de redes sociales en cuestión, pero a menudo incluirá su nombre, dirección de correo electrónico y foto de perfil, así como otra información que elija hacer pública en dicha plataforma de redes sociales.',
      socialLoginsDetails: 'Usaremos la información que recibimos solo para los fines que se describen en este aviso de privacidad o que se le aclaran de otro modo en FeedGears. Tenga en cuenta que no controlamos y no somos responsables de otros usos de su información personal por parte de su proveedor de redes sociales externo. Le recomendamos que revise su aviso de privacidad para comprender cómo recopilan, usan y comparten su información personal, y cómo puede configurar sus preferencias de privacidad en sus sitios y aplicaciones.',
      internationalInformationTransfers: 'Transferencias internacionales de información',
      internationalInformationTransfersSummary: 'Podemos transferir, almacenar y procesar su información en países distintos al suyo.',
      internationalInformationTransfersDetails: 'Nuestros servidores están ubicados en los Estados Unidos. Si accede a FeedGears desde fuera de los Estados Unidos, tenga en cuenta que su información puede ser transferida, almacenada y procesada por nosotros en nuestras instalaciones y por aquellas de terceros con quienes podemos compartir su información personal, en los Estados Unidos. Estados y otros países.',
      internationalInformationTransfersDetailsFurther: 'Si reside en el Espacio Económico Europeo (EAA) o el Reino Unido (RU), es posible que estos países no tengan necesariamente leyes de protección de datos u otras leyes similares tan completas como las de su país. Tomaremos todas las medidas necesarias para proteger su información personal de acuerdo con este aviso de privacidad y la ley aplicable.',
      whatAreYourPrivacyRights: '¿Cuáles son sus derechos de privacidad?',
      yourPrivacyRightsSummary: 'Puede revisar, cambiar o cancelar su cuenta en cualquier momento.', 
      yourPrivacyRightsDetails: 'No distribuiremos su información personal a terceros sin su consentimiento.',
      yourConsent: 'Tu consentimiento',
      yourConsentSummary: 'Al usar nuestro sitio o nuestras aplicaciones, usted acepta nuestra política de privacidad.',
      doWeMakeUpdates: '¿Hacemos actualizaciones a este aviso?',
      doWeMakeUpdatesSummary: 'Sí, actualizaremos este aviso según sea necesario para cumplir con las leyes pertinentes.',
      howCanYouContactUs: '¿Cómo puede ponerse en contacto con nosotros acerca de este aviso?',
      // aria labels 
      visitLSDevBlogAriaLabel: 'Visite el blog de desarrollo de Lost Sidewalk en una nueva pestaña',
      emailSupportArialLabel: 'Abra su cliente de correo electrónico para enviar un correo electrónico al soporte de FeedGears',
      visitLSTwitterAriaLabel: 'Visite el Twitter de Lost Sidewalk en una nueva pestaña',
      visitLSGithubArialLabel: 'Visite Lost Sidewalk Github en una nueva pestaña',
      visitLSTwitchAriaLabel: 'Visite Lost Sidewalk en Twitch en una nueva pestaña',
      visitLSDiscordAriaLabel: 'Visite Lost Sidewalk Discord en una nueva pestaña',
      visitLSHomepage: 'Visite la página de inicio de Lost Sidewalk',
      goToQueueDashboardAriaLabel: 'Ir al panel de colas',
      switchModeAriaLabel: 'Cambiar a tema claro u oscuro',
      cycleGridLayoutAriaLabel: 'Cambiar al diseño de cuadrícula',
      cycleTableLayoutAriaLabel: 'Cambiar a diseño tabular', // TODO: fix this 
      logoutArialLabel: 'Cerrar sesión',
      goToSettingsAriaLabel: 'Ir a la configuración de la cuenta',
      goToHelpAriaLabel: 'Mostrar ayuda',
      shareWith_twitter_ariaLabel: 'Compartir con Twitter',
      shareWith_facebook_ariaLabel: 'Compartir con Facebook',
      shareWith_telegram_ariaLabel: 'Compartir con Telegram',
      shareWith_linkedIn_ariaLabel: 'Compartir con LinkedIn',
      shareWith_blogger_ariaLabel: 'Compartir con Blogger',
      shareWith_buffer_ariaLabel: 'Compartir con Buffer',
      shareWith_hootsuite_ariaLabel: 'Compartir con Hootsuite',
      // image alts 
      queuePageScreenshot: 'Captura de pantalla de la página de cola de FeedGears',
      queueLogoImage: 'Imagen del logotipo de la cola',
      feedLogoImage: 'Imagen del logotipo de fuente RSS',
      rssLogo: 'logotipo RSS',
      postThumbnailImage: 'Publicar imagen en miniatura',
      postEnclosureImage: 'Publicar imagen del recinto',
      postITunesImage: 'Publicar imagen de iTunes',
      postMediaContentImage: 'Publicar imagen de contenido multimedia', 
      postMediaThumbnail: 'Publicar miniatura de medios',
      oAuth2ProfileImage: 'Imagen de perfil de OAuth2',
      defaultOAuth2ProfileImage: 'Imagen de perfil predeterminada de OAuth2',
    },
    en: {
      // generic 
      somethingHorribleHappened: 'Something horrible happened.  Please try again in a few moments.',
      privacyPolicy: 'Privacy Policy',
      cancel: 'Cancel',
      filter: 'Filter',
      first: 'First',
      previous: 'Previous',
      next: 'Next',
      last: 'Last',
      username: 'Username',
      password: 'Password',
      submit: 'Submit',
      subscribe: 'Subscribe',
      subscribed: 'Subscribed!',
      emailAddress: 'Email address',
      inDevelopment: 'Sorry, this section of FeedGears isn\'t quite ready yet.  Check back in a few days!',
      // auth 
      accountRecovery: 'Account recovery',
      registerHere: 'FeedGears is free.  Create an account here.',
      unableToCompleteYourRequest: 'We weren\'t able to complete your request.  Please try to login using another method.',
      usernameAndPasswordAreRequired: 'Username and password are required.',
      passwordIsRequired: 'Password is required.',
      usernameIsRequired: 'Username is required.',
      signinWithGoogle: 'Sign in with Google',
      pwResetRequestMessage: 'Enter your username and email address.  We\'ll send a password reset link to your verified email address."',
      checkEmailForFurther: 'Check your email to further instructions.',
      newPassword: 'New password',
      confirmNewPassword: 'Confirm new password',
      enterAndConfirmNewPw: 'Enter and confirm your new password.',
      pwUpdated: 'Password updated.',
      registrationRequirements: 'Username, email address, and password are required in order to register.',
      youHaveBeenLoggedOut: 'You\'ve been logged out.',
      clickHereToStartOver: 'Click here to start over.',
      // landing 
      createAnAccount: 'Create an account',
      whatIsFeedGears: 'A secure, private, accessible feed reader.',
      whyIsFeedGearsFree: 'Free forever because we love RSS',
      devBlog: 'Dev Blog',
      docs: 'Docs',
      api: 'API',
      email: 'Email',
      twitter: 'Twitter',
      github: 'Github',
      twitch: 'Twitch',
      discord: 'Discord',
      copyright: 'COPYRIGHT',
      contactUsWithQuestionsViaEmail: 'Contact Lost Sidewalk Software with questions via email.', 
      // confirmation dialog 
      confirm: 'Confirm',
      // go back
      goBack: 'Go back.',
      // min-max
      collapseThisPanel: 'Collapse this panel',
      restoreThisPanel: 'Restore this panel',
      // navbar button components 
      login: 'Login', 
      logout: 'Logout',
      settings: 'Settings', 
      help: 'Help',
      switchMode: 'Switch display mode',
      cycleGridLayout: 'Switch to grid layout',
      cycleTableLayout: 'Switch to tabular layout',
      // queue dashboard buttons 
      createNewQueue: 'Create a new queue',
      uploadOPML: 'Upload OPML',
      weWillNotSellOrDiscloseYourInformation: 'Please note that we will neve sell or disclose your personal information to anyone.',
      // queue select button 
      showMoreInfo: 'Show details',
      hideMoreInfo: 'Hide details',
      addSubscriptions: 'Add subscriptions',
      manageSubscriptions: 'Manage subscriptions',
      deleteThisQueue: 'Delete this queue',
      subscriptions: 'SUBSCRIPTIONS',
      publications: 'PUBLICATIONS',
      zeroSubscriptions: '0 subscriptions',
      starredArticlesAvailableHere: 'The starred articles in this queue are available in the following feeds.',
      metricsNotYetAvailable: 'Metrics are not yet available for this feed.',
      // queue config image field 
      clickToChangeQueueImage: 'Click here to change the queue image.',
      clickToAddQueueImage: 'Click here to add a queue image.', 
      unableToFetchAnImage: 'We weren\'t able to fetch an image.  Please try again later.',
      unableToUseThisImage: 'We weren\'t able to use this image.  Please try another, and note that the maximum size for image files is 1M.',
      // queue config panel 
      queueIdentifier: 'Queue identifier', 
      queueIdentifierHelpText: 'The queue identifier is a short textual description of this queue.  It is case insensitive, and must container only numbers, letters, dashes, or underscores.  This identifier can used to locate the starred feed for this queue.  Click for more information.',
      queueTitle: 'Queue title', 
      queueTitleHelpText: 'The queue title is a textual description of this queue that appears on the queue dashboard.',
      queueImage: 'Queue image', 
      queueDescription: 'Queue description', 
      queueDescriptionHelpText: 'This value is a more verbose textual description of this queue.  It appears in the published RSS/ATOM feed for this queue.',
      queueFeedGenerator: 'Generator', 
      queueFeedGeneratorHelpText: 'This value appears as the \'generator\' in the published RSS/ATOM feed for this queue.',
      queueFeedCopyright: 'Copyright', 
      queueFeedCopyrightHelpText: 'This value appears as the \'copyright\' in the published RSS/ATOM feed for this queue.',
      queueFeedLanguage: 'Language', 
      queueFeedLanguageHelpText: 'This value appears as the value for the \'language\' field in the published RSS/ATOM feed for this queue.',
      fillOutAllRequiredFields: 'Fill out all required fields',
      // tooltips 
      updateThisQueue: 'Update this queue',
      updateThisQueueAndClose: 'Update this queue and close',
      // buttons 
      update: 'Update',
      updateAndClose: 'Update and close',
      // tooltips 
      saveThisQueue: 'Save this queue',
      saveThisQueueAndClose: 'Save this queue and close',
      // buttons 
      save: 'Save',
      saveAndClose: 'Save and close',
      // 
      queueProperties: 'Queue Properties',
      rssFeedDiscovery: 'RSS Feed Discovery',
      // rss feed info 
      toggleAuthorFilter: 'Toggle filtering on this author',
      authorColon: 'Author:',
      lastPublishedColon: 'Last published:',
      toggleCategoryFilter: 'Toggle filtering on this category', 
      toggleLanguageFilter: 'Toggle filtering on this language',
      toggleDocStringFilter: 'Toggle filtering on this doc string',
      toggleEncodingFilter: 'Toggle filtering on this encoding',
      toggleManagingEditorFilter: 'Toggle filter by this managing editor',
      managingEditorColon: 'Managing editor:', 
      toggleWebmasterFilter: 'Toggle filtering on this webmaster', 
      webmasterColon: 'Webmaster:', 
      httpStatusCode: 'HTTP status code',
      redirectHttpStatusCode: 'Redirect HTTP status code', 
      feedAlsoAvailableInHttps: 'This feed is also available in HTTPS.', 
      sampleEntries: 'Recent articles',
      recommendedFeeds: 'Similar feeds',
      // feed collections browser 
      loadingCollections: 'LOADING COLLECTIONS...',
      browseCollectionsByCategory: 'BROWSE COLLECTIONS BY CATEGORY',
      topNews: 'News',
      investing: 'Investing',
      technology: 'Technology',
      business: 'Business',
      science: 'Science',
      creative: 'Creative',
      lifestyle: 'Lifestyle',
      // feed catalog 
      feedCatalog: 'FEED CATALOG',
      nFeedsMatchOnPageM: 'FEEDS MATCH, SHOWING PAGE',
      categoryColon: 'Category:',
      languageColon: 'Language:',
      docsColon: 'Docs:',
      encodingColon: 'Encoding:',
      feedTypeColon: 'Feed Type:',
      generatorColon: 'Generator:',
      removeThisFilter: 'Remove this filter',
      subscribeToThisFeed: 'Subscribe to this feed',
      youAreSubscribed: 'Subscribed!',
      // subscription config 
      yourSubscriptions: 'YOUR SUBSCRIPTIONS',
      showingPageN: 'Showing page',
      addFeedFromURL: 'Add feed from a URL',
      searchFeedCatalog: 'Search our feed catalog',
      browseFeedCollections: 'Browse feed collections',
      subscriptionNofM: 'SUBSCRIPTION',
      addANewSubscription: 'ADD A NEW SUBSCRIPTION',
      feedUrl: 'FEED URL',
      credentialsUseMessage: '* The following credentials will be supplied if this feed requests authentication.',
      unableToFetchCatalog: 'We weren\'t able to fetch our feed catalog.  Please try again later.',
      discovery: 'Discovery', 
      auth: 'Auth',
      unsubscribe: 'Unsubscribe',
      subscriptionAdded: 'Subscription added',
      subscriptionUpdated: 'Subscription updated',
      subscriptionDeleted: 'Subscription deleted',
      // post feed filter  
      articleQueue: 'ARTICLE QUEUE',
      refreshQueues: 'Refresh queues', 
      markQueueAsRead: 'Mark this queue as read',
      toggleSortOrder: 'Toggle sort direction',
      showFilterOptions: 'Show filter options', 
      // post feed filter pills 
      allSubscriptions: 'all subscriptions',
      viewingColon: 'Viewing:',
      resetToDefault: 'Reset to default',
      unread: 'UNREAD', 
      readLater: 'READ-LATER',
      read: 'READ',
      starred: 'STARRED',
      // help panel 
      dismiss: 'Dismiss',
      configureSelectedQueue: 'Manage subscriptions in the selected queue',
      markSelectedQueueAsRead: 'Mark the selected queue as read',
      addSubscriptionToSelectedQueue: 'Add a subscription to selected queue',
      starSelectedPost: 'Star the selected post',
      toggleReadStatusSelectedPost: 'Toggle the selected post read/unread',
      openOriginalArticleSelectedPost: 'Open selected post URL in a new tab',
      showUnread: 'Show unread', 
      showStarred: 'Show starred',
      showReadLater: 'Show read-later',
      showRead: 'Show read',
      search: 'Search',
      // iTunes
      explicit: 'EXPLICIT',
      closedCaptioned: 'Closed Captioned',
      // post media 
      media: 'MEDIA', 
      // community 
      nViews: 'VIEWS',
      tags: 'TAGS', 
      // post media content 
      audioChannelsColon: 'AUDIO CHANNELS:',
      bitRateColon: 'BIT RATE:',
      durationColon: 'DURATION:',
      expressionColon: 'EXPRESSION:',
      fileSizeColon: 'FILE SIZE:',
      frameRateColon: 'FRAME RATE:',
      heightColon: 'HEIGHT:',
      widthColon: 'WIDTH:',
      samplingRateColon: 'SAMPLING RATE:',
      // opml 
      opmlFilesColon: 'OPML FILES:',
      previewThisFile: 'Preview this file in a new window.', 
      opmlFilesContainErrors: 'Your files contain the following problems.  Please resolve these issues and re-attempt your upload.',
      weWillCreateTheFollowingSubscriptions: 'We will create the following queues from your OPML file(s):',
      selectAnOpmlFile: 'Select an OPML file',
      addAnOpmlFile: 'Add an OPML file', 
      finalizeUpload: 'Finalize upload',
      continue: 'Continue',
      addAtLeastOneFile: 'Add at least one OPML file to continue.',
      continueToStep2: 'Continue to step 2', 
      // post feed 
      confirmDeleteQueue: 'Please confirm that you want to delete this queue. This action is irreversible.', 
      confirmMarkQueueAsRead: 'Please confirm that you want to mark all items in this queue as read.', 
      queueDashboard: 'FEED DASHBOARD', 
      noArticlesInQueue: 'There are no articles in this queue.  Add additional subscriptions or wait for more articles to be imported.', 
      endOfQueueReached: 'You have reached the end of this queue.  Add additional subscriptions or wait for more articles to be imported.', 
      queueSettings: 'QUEUE SETTINGS', 
      opmlUpload: 'OPML UPLOAD', 
      refreshFailedDueToColon: 'Refresh failed due to:',
      noMessage: 'no message',
      queueUpdated: 'Queue updated.  We\'re sorting out your subscriptions in the background.  This process may take several minutes.',
      queueCreated: 'Queue created.  We\'re sorting out your new subscriptions in the background.  This process may take several minutes.',
      nQueuesCreated: ' queues created.  We\'re sorting out your new subscriptions in the background.  This process may take several minutes.',
      clickToLoadMore: 'Click here to load more', 
      // post item 
      showPostDetails: 'Show post details', 
      showPostCategories: 'Show post categories',
      showPostSharing: 'Show post sharing options',
      shareWith_twitter: 'Share with Twitter',
      shareWith_facebook: 'Share with Facebook',
      shareWith_telegram: 'Share with Telegram',
      shareWith_linkedIn: 'Share with LinkedIn',
      shareWith_blogger: 'Share with Blogger',
      shareWith_buffer: 'Share with Buffer',
      shareWith_hootsuite: 'Share with Hootsuite',
      goToNextPost: 'Go to next post',
      goToPreviousPost: 'Go to previous post',
      goToFirstPost: 'Go to first post',
      goToLastPost: 'Go to last post',
      markPostAsUnread: 'Mark as unread',
      markPostAsRead: 'Mark as read',
      markPostAsReadLater: 'Mark as read-later',
      unmarkPostAsReadLater: 'Unmark as read-later', 
      starThisPost: 'Star this post',
      unstarThisPost: 'Un-star this post',
      openOriginalArticle: 'Open original article',
      description: 'DESCRIPTION',
      links: 'LINKS', 
      postComments: 'COMMENTS', 
      author: 'AUTHOR',
      authors: 'AUTHORS', 
      updated: 'UPDATED',
      published: 'PUBLISHED',
      contributors: 'CONTRIBUTORS', 
      // settings 
      accountSettings: 'ACCOUNT SETTINGS', 
      usernameColon: 'USERNAME:', 
      emailAddressColon: 'EMAIL ADDRESS:', 
      applyChanges: 'Apply Changes',
      deactivateYourAccount: 'Deactivate Your Account',
      downloadYourData: 'Download Your Data', 
      permanentlyDeleteYourAccount: 'Permanently Delete Your Account',
      sendPasswordResetEmail: 'Send Password Reset Email', 
      resetPassword: 'Reset Password',
      updateNotificationPreferences: 'Update Notification Preferences', 
      emailNotificationsAreDisabled: 'Email notifications are currently disabled.',
      emailNotificationsAreEnabled: 'Email notifications are currently enabled.',
      enableAccountAlertsNotifications: 'Enable this option to receive account alerts and maintenance notifications.',
      enableProductNotifications: 'Enable this option to receive occasional emails about production notifications and new features.',
      enableSelectedNotifications: 'Enable Selected Notifications',
      disableSelectedNotifications: 'Disable All Notifications', 
      yourSubscriptionWasCanceled: 'Your subscription was canceled, and will not renew.',
      currentPeriod: 'CURRENT PERIOD',
      endedAt: 'ENDED AT',
      willEndAt: 'WILL END AT',
      statusColon: 'STATUS:',
      amountDueColon: 'AMOUNT DUE:',
      amountPaidColon: 'AMOUNT PAID:',
      amountRemainingColon: 'AMOUNT REMAINING:',
      customerEmailAddressColon: 'CUSTOMER EMAIL ADDRESS:',
      customerNameColon: 'CUSTOMER NAME:',
      invoiceUrlColon: 'INVOICE URL:',
      productColon: 'PRODUCT:',
      mostRecentInvoice: 'MOST RECENT INVOICE',
      clickHere: 'Click here', 
      cancelSubscription: 'Cancel subscription',
      resumeSubscription: 'Resume subscription',
      pleaseConsiderSubscribing: 'Please consider subscribing to FeedGears.  We are supported 100% by the user community.',
      checkout: 'Checkout',
      settingsUpdated: 'Settings updated', 
      updateLightTheme: 'Click here to save your changes to the light theme',
      updateDarkTheme: 'Click here to save your changes to the dark theme',
      themeSettingsUpdated: 'Theme settings updated', 
      opmlExportDownloaded: 'OPML export downloaded',
      yourSubscriptionWasCanceledClickToResume: 'Your subscription was canceled.  To resume, click \'Resume Subscription\' on this page.', 
      yourSubscriptionWasResumed: 'Your subscription was resumed',
      // docs 
      feedGearsDocumentation: 'FEEDGEARS DOCUMENTATION', 
      // api 
      feedGearsApi: 'FEEDGEARS API',
      // order confirmation
      thankYouForYourOrder: 'THANK YOU FOR YOUR ORDER',
      yourOrderIsConfirmed: 'Your order is confirmed.',
      clickHereToReturnToTheApp: 'Click here to return to the app.', 
      // verification callback 
      thanksForVerifying: 'Thanks for verifying!  Your account status has been updated.',
      // privacy policy 
      feedGearsPrivacyPolicy: 'FEEDGEARS PRIVACY POLICY', 
      whatInformationDoWeCollect: 'What information do we collect?',
      whatWeCollectSummary: 'We collect personal information that you provide to us.',
      whatWeCollectDetails: 'We collect personal information that you voluntarily provide to use when you register on FeedGears, express an interest in obtaining information about us or FeedGears, when you participate in activities on FeedGears, or otherwise when you contact us.',
      whatWeCollectImportantDetails: 'We do not process sensitive information.', 
      whatWeCollectFurtherDetails: 'All personal information that you provide to us must be true, complete, and accurate, and you must notify us of any changes to such personal information.', 
      someCollectionIsAutomatic: 'Some information is automatically collected',
      automaticCollectionDetails: 'Some information--such as your Internet Protocol (IP) address and/or browser and device characteristics--is collected automatically when you visit FeedGears.  This information (operating system, language preferences, referring URLs, device name, country, location, information about how and when you use FeedGears, and other technical information) does not reveal your specific identity (like your name or contact information) but may include device and usage information.  This information is primarily needed to maintain the security and operation of FeedGears, and for our internal analytics and reporting purposes.', 
      howDoWeProcess: 'How do we process your information?',
      howDoWeProcessSummary: 'We process your information to provide, improve, and administer FeedGears, communicate with you, for security and fraud prevention, and to comply with law.  We may also process your information for other purposes with your consent.',
      socialLogins: 'Social logins',
      socialLoginsSummary: 'FeedGears offers you the ability to register and login using your third-party social media account details (like Google or Github logins).  Where you choose to do this, we will receive certain profile information about you from your social media provider.  The profile information we receive may vary depending on the social media provider concerned, but will often include your name, email address, and profile picture, as well as other information you choose to make public on such a social media platform.',
      socialLoginsDetails: 'We will use the information we receive only for the purposes that are described in this privacy notice or that are othrerwise made clear to you on FeedGears.  Please note that we do not control, and are not responsible for, other uses of your personal information by your third-party social media provider.  We recommend that you review their privacy notice to understand how they collect, use, and share your personal infromation, and how you can set your privacy preferences on their sites and apps.',
      internationalInformationTransfers: 'International information transfers',
      internationalInformationTransfersSummary: 'We may transfer, store, and process your information in countries other than your own.',
      internationalInformationTransfersDetails: 'Our servers are located in the United States.  If you are acessing FeedGears from outside the United States, please be aware that your information may be transferred to, stored, and processed by us in our facilities and by those of third-parties with whom we may share your personal information, in the United States and other countries.',
      internationalInformationTransfersDetailsFurther: 'If you are a resident in the European Economic Area (EAA) or United Kingdom (UK), then these countries may not necessarily have data protection laws or other simliar laws as comprehensive as those in your country.  We will take all necessary measures to protected your personal information in accordance with this privacy notice and applicable law. ',
      whatAreYourPrivacyRights: 'What are your privacy rights?',
      yourPrivacyRightsSummary: 'You may review, change, or terminate your account at any time.', 
      yourPrivacyRightsDetails: 'We will not distribute your personal information to outside parties without your consent.',
      yourConsent: 'Your consent',
      yourConsentSummary: 'By using our site or apps, you consent to our privacy policy.',
      doWeMakeUpdates: 'Do we make updates to this notice?',
      doWeMakeUpdatesSummary: 'Yes, we will update this notice as necessary to stay compliant with relevant laws.',
      howCanYouContactUs: 'How can you contact us about this notice?',
      // aria labels 
      visitLSDevBlogAriaLabel: 'Visit the Lost Sidewalk dev blog in a new tab',
      emailSupportArialLabel: 'Open your email client to send email to FeedGears support',
      visitLSTwitterAriaLabel: 'Visit the Lost Sidewalk Twitter in a new tab',
      visitLSGithubArialLabel: 'Visit the Lost Sidewalk Github in a new tab',
      visitLSTwitchAriaLabel: 'Visit Lost Sidewalk on Twitch in a new tab',
      visitLSDiscordAriaLabel: 'Visit the Lost Sidewalk Discord in a new tab',
      visitLSHomepage: 'Visit the Lost Sidewalk homepage',
      goToQueueDashboardAriaLabel: 'Go to queue dashboard',
      switchModeAriaLabel: 'Switch to light or dark theme',
      cycleGridLayoutAriaLabel: 'Switch to grid layout',
      cycleTableLayoutAriaLabel: 'Switch to table layout',
      logoutArialLabel: 'Logout',
      goToSettingsAriaLabel: 'Go to account settings',
      goToHelpAriaLabel: 'Show help',
      shareWith_twitter_ariaLabel: 'Share with Twitter',
      shareWith_facebook_ariaLabel: 'Share with Facebook',
      shareWith_telegram_ariaLabel: 'Share with Telegram',
      shareWith_linkedIn_ariaLabel: 'Share with LinkedIn',
      shareWith_blogger_ariaLabel: 'Share with Blogger',
      shareWith_buffer_ariaLabel: 'Share with Buffer',
      shareWith_hootsuite_ariaLabel: 'Share with Hootsuite',
      // image alts 
      queuePageScreenshot: 'FeedGears queue page screenshot',
      queueLogoImage: 'Queue logo image',
      feedLogoImage: 'Feed logo image',
      rssLogo: 'RSS logo',
      postThumbnailImage: 'Post thumbnail image',
      postEnclosureImage: 'Post enclosure image',
      postITunesImage: 'Post iTunes image',
      postMediaContentImage: 'Post media content image', 
      postMediaThumbnail: 'Post media thumbnail',
      oAuth2ProfileImage: 'OAuth2 profile image',
      defaultOAuth2ProfileImage: 'Default OAuth2 profile image',
    },
  }
});

createApp(App, {})
    .use(NewsGearsWebPlugin, {})
    .use(NewsGearsThemePlugin)
    .use(router)
    .use(autoAnimatePlugin)
    .use(VuePlyr, {
      plyr: {}
    })
    .use(VueAnnouncer)
    .use(i18n)
    .use(Vue3NativeNotification, {
      requestOnNotify: true
    })
    .mount('#app');
